# Generated by Django 4.0.2 on 2022-05-25 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrugName', models.CharField(max_length=200)),
                ('Cost', models.IntegerField()),
                ('Profit', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Measurement', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(max_length=200)),
                ('Amount', models.FloatField(max_length=200)),
                ('Date', models.DateField(auto_now_add=True)),
                ('User', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Residence', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('PatientId', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Treated', models.CharField(max_length=200)),
                ('PatientId', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Salary', models.CharField(max_length=200)),
                ('PlaceOfResidence', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('Phone1', models.CharField(blank=True, max_length=200, null=True)),
                ('EmployMentDate', models.DateField()),
                ('ImageField', models.ImageField(upload_to='')),
                ('Email', models.EmailField(max_length=200)),
                ('CloseRelative', models.CharField(max_length=100)),
                ('CloseRelativePhone1', models.CharField(max_length=100)),
                ('CloseRelativePhone2', models.CharField(max_length=100)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drugs.roles')),
            ],
        ),
    ]
