# Generated by Django 4.0.2 on 2022-05-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Measurement', models.CharField(default='Tablets', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='drug',
            name='Measurement',
        ),
        migrations.AddField(
            model_name='drug',
            name='Measured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drugs.measurement'),
        ),
    ]
