# Generated by Django 4.0.2 on 2022-05-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drugs', '0002_measurement_remove_drug_measurement_drug_measured'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.RenameModel(
            old_name='Treatments',
            new_name='Treatment',
        ),
    ]
