# Generated by Django 4.0.2 on 2022-05-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drugs', '0003_rename_expenses_expense_rename_patients_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balwadde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Residence', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('PatientId', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Residence', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('PatientId', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
