# Generated by Django 4.0.2 on 2022-05-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Drugs', '0004_balwadde_patients_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drug_Order', models.CharField(blank=True, max_length=200)),
                ('ClientID', models.CharField(max_length=15)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.CharField(max_length=500)),
                ('Description', models.TextField(blank=True, max_length=1000)),
                ('Date', models.DateField()),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drugs.employee')),
            ],
        ),
    ]
